게임 시작시 카드 올바르게 생성되는지 확인하는 테스트 코드 추가
Seeyou2000/SE_UNO_Project pull request #18
Opened 2023-05-01 08:09 UTC by whuchubird

정상적으로 덱을 생성했을 때 총 카드 개수와 코드를 통해 덱 생성 시의 총 카드 개수 비교하여 누락, 중복을 체크했습니다

2023-05-01 08:23 UTC, gidongkwon requested changes

2023-05-01 08:23 UTC, gidongkwon commented on game/gameplay/gamestate_test.py
> +    assert len(game_state.game_deck.cards) == full_deck_num
전체 숫자를 체크하는것도 물론 좋은데 cards에 정말로 각각이 원하는만큼 들어있는지 검사하는 코드가 추가되었으면 좋겠습니다.

2023-05-01 10:17 UTC, whuchubird commented on game/gameplay/gamestate_test.py
> +    assert len(game_state.game_deck.cards) == full_deck_num
덱의 카드 리스트를 받아와 셔플되지 않은 새로운 덱을 생성한 후 서로 비교하려 했는데, 스트링이 동일하지만 두 카드를 다른 오브젝트로 인식해서 card.py파일에 각 카드 정보를 리턴하는 info함수를 추가했는데 이렇게 진행해도 괜찮을까요? 일단 해당 함수 사용하면 테스트코드가 제대로 동작하긴 합니다.

2023-05-01 10:18 UTC, whuchubird commented on game/gameplay/gamestate_test.py
> +    assert len(game_state.game_deck.cards) == full_deck_num
덱의 카드 리스트를 받아와 셔플되지 않은 새로운 덱을 생성한 후 서로 비교하려 했는데, 두 카드의 스트링이 동일해도 해당 카드들을 서로 다른 오브젝트로 인식해서 card.py파일에 각 카드 정보를 리턴하는 info함수를 추가했는데 이렇게 진행해도 괜찮을까요? 일단 해당 함수 사용하면 테스트코드가 제대로 동작하긴 합니다.

2023-05-01 11:03 UTC, gidongkwon commented
저는 덱을 만드는 코드랑 똑같은 코드를 써서 리스트를 만들어 테스트를 하는 대신 코드는 좀 길어지더라도 조건에 맞는 카드 숫자를 셌으면 좋겠습니다.
이유는 크게 두 가지 있습니다.
1. 테스트 코드에서 조건이 바로 보여지지 않습니다.
2. 테스트를 같은 코드를 사용하게 구성하면 create_full_deck_cards 함수의 내용을 수정해야 될 때가 왔을 때 테스트 코드에도 그냥 복사 붙여넣기하게 될 것 같아서 테스트 자체의 의미가 없어질 것 같습니다.

구현은 이 링크를 참조해보시면 도움이 될 것 같습니다.
https://stackoverflow.com/questions/2643850/what-is-a-good-way-to-do-countif-in-python

2023-05-01 11:05 UTC, gidongkwon requested changes

2023-05-01 11:05 UTC, gidongkwon commented on game/gameplay/card.py
> +        return f"[카드 색: {self.color}, 숫자: {self.number}, 능력: {self.ability}]"
이 부분은 위의 __str__ 과 내용이 완전히 겹치는데, 카드의 비교를 위해서는 __eq__를 구현해주시는게 가장 좋고, 그게 아니더라도 str을 활용해서 비교하는게 가장 좋은 것 같습니다.

__str__은 str(변수)를 하면 나오는 내용을 정의하는 함수입니다

2023-05-02 05:47 UTC, gidongkwon commented
개선의 여지가 있는 코드라고 생각되는데, 제가 처음부터 끝까지 글로 전달드리기에는 좀 양이 많을 수 있어서 괜찮으시다면 지금 코드를 바탕으로 제가 수정한 뒤에 설명드리겠습니다.

2023-05-02 06:21 UTC, gidongkwon commented
바뀐 부분과 그 이유입니다

1. 카드를 문자열로 변환하지 않고 카드 그 자체로 취급했습니다.
- 이유: 속성이 같은지 검사해야하는데 문자열로 변환한 다음 in 으로 검사하는 것은 문자열의 표현 방식이 바뀌면 깨질 수 있는 구조적으로 취약한 구현이라고 생각합니다.

2. count_deck_if 함수를 구현해서 로직상 여러 테스트에 공통적으로 쓰이지만 가독성을 해치는 부분에 이름을 붙여주고 격리했습니다. 

3. error를 세지 않고 숫자 조건을 변수로 명시한 후 조건 자체를 assert 했습니다.
- 이유: 이 방법이 만약 기존 테스트를 깨먹는 코드를 작성했을 때 바로 어떤 문제가 생겼는지 알 수 있는 가장 직관적인 방법이라고 생각하는데, 그 이유는 에러 숫자라는건 반복문으로 돌리는 각각의 케이스에 대해서 검사하는게 아니라 전체가 다 계산된 후의 결과이기 때문에 (만약 특정 케이스에서 +1되어있고 또 다른 케이스에서 -1되어있는 경우는 잡을 수 없는 코드이기 때문에) 정합성이 쉽게 깨질 수 있다고 생각합니다.

2023-05-02 06:25 UTC, gidongkwon commented
@whuchubird 일단 제 임의로 바꿔봤는데, 혹시 걸리는 부분이 있으시면 말씀해주세요

2023-05-02 14:02 UTC, whuchubird commented
지금 코드로 하면 될 것 같습니다

2023-05-02 14:05 UTC, merged