업적이 달성됐을 때 실시간으로 반영하는 코드 추가 및 10턴 안에 승리 업적 추가
Seeyou2000/SE_UNO_Project pull request #25
Opened 2023-05-08 16:58 UTC by SDHSeoulTech

각 업적이 달성될만한 노드에서 업적 달성 조건 체크에 필요한 정보를 보내주고
ingamescene의 각 함수에서 조건을 체크해 조건이 맞을 경우 achievements.py의 업적의 값을 바꿔줍니다.
10턴 안에 승리 업적 달성 시 달성 여부가 바뀌는 것과 달성 시간이 정상적으로 저장되는 것을 확인하였습니다.

2023-05-08 17:32 UTC, gidongkwon requested changes

2023-05-08 17:32 UTC, gidongkwon commented on game/ingame/ingamescene.py
> +        self.flow.events.on("game_end", self.check_win_less_10turn)
"game_end"를 상수로 쓰는 대신 선언해둔 GameFlowMachineEventType.GAME_END 이넘값을 썼으면 좋겠습니다.

2023-05-08 17:32 UTC, gidongkwon commented on game/gameplay/flow/gameend.py
> +            "game_end",
"game_end"를 상수로 쓰는 대신 선언해둔 GameFlowMachineEventType.GAME_END 이넘값을 썼으면 좋겠습니다.

2023-05-09 01:37 UTC, SDHSeoulTech commented on game/ingame/ingamescene.py
> +        self.flow.events.on("game_end", self.check_win_less_10turn)
수정했습니다!

2023-05-09 01:37 UTC, SDHSeoulTech commented on game/gameplay/flow/gameend.py
> +            "game_end",
수정했습니다!

2023-05-09 01:38 UTC, merged