업적메뉴씬 구현
Seeyou2000/SE_UNO_Project pull request #27
Opened 2023-05-14 15:48 UTC by whuchubird

1.왼쪽 상단에 뒤로가기 버튼 생성
2.화면에 (아이콘) (업적이름) 형태로 배치
-> 업적 배치의 경우 한줄로 다 넣기에는 게임 완성 시 너무 빽빽해질거 같아 두줄로 나눠서 배치했습니다.
3.클리어 한 업적의 경우 아이콘 위에 클리어 표시가 덮어써짐
현재 구현된 업적은 1개라 1개만 연동 시키고 나머지는 임의로 5개는 클리어 안되었을 때 상태, 5개는 클리어 되었을 때 상태로 배치해두었습니다. 업적 추가되는대로 연동 해놓겠습니다

2023-05-15 10:35 UTC, gidongkwon commented
업적 설명과 달성일자가 빠져있습니다. 추가 부탁드립니다.

2023-05-15 10:36 UTC, gidongkwon commented
추가로, 업적 표시에 사용되는 각 항목이 좀 더 작아도 상관없으니 저희 게임이 지원하는 가장 작은 해상도인 1280*720 화면에서 이상하게 보이지 않도록 배치해주세요.

2023-05-16 05:29 UTC, gidongkwon commented
<img width="129" alt="image" src="https://github.com/Seeyou2000/SE_UNO_Project/assets/2127206/abddc6e5-32c5-41a5-abf1-740789b68eb8">

1. 혹시 아이콘이 이렇게 보이는게 의도된 부분일까요? 아니면 오른쪽 아래에 딱 붙는게 의도인가요?
2. 리소스 위치 resources/images 아래로 옮기면 좋을 것 같습니다.

코드쪽으로 리뷰할 거리가 좀 많은데 마감이 얼마 남지 않았으므로 위 사항만 정리되면 머지하겠습니다.

2023-05-16 05:31 UTC, gidongkwon commented
추가적으로 직접 작성한 부분의 린트 오류도 잡아서 커밋해주세요. `ruff .` 사용해서 나오는 사항들 수정해주시면 됩니다.

2023-05-16 05:40 UTC, whuchubird commented
아이콘은 중앙에 두려고 의도한거에요. 그냥 임의로 만들다 보니 약간 생긴게 왼쪽 아래에 붙어야 할 것 같이 만들게 됐어요... ㅎㅎ

2023-05-16 05:55 UTC, gidongkwon requested changes

2023-05-16 05:55 UTC, gidongkwon commented on game/ingame/ingamescene.py
> +        )
이 부분 어떤 것 때문에 있는걸까요?

2023-05-16 05:56 UTC, whuchubird commented on game/ingame/ingamescene.py
> +        )
어 그거 왜 들어갔지 빼둘게요
다음 작업 건들여보던게 딸려간거 같요

2023-05-16 05:58 UTC, merged